apiVersion: v1
kind: Service
metadata:
  name: shine-project
  namespace: shine-app
  labels:
    app.kubernetes.io/name: shine-project
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: shine-gitops-platform
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: shine-project
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3130
      targetPort: http
      protocol: TCP

